framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    # Configure AMQP exchanges here
                    # Use the 'messages' exchange of type 'topic'
                    exchange:
                        name: messages
                        type: topic

                    # Queue settings
                    queues:
                        main: ~ # Queue name: 'main'
            failed:
                dsn: 'doctrine://default?queue_name=failed'
                options:
                    # These options are allowed here
                    use_notify: true
                    check_delayed_interval: 60000
            # sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            # Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            # Symfony\Component\Notifier\Message\ChatMessage: async
            # Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            'App\Booking\Application\Message\SendConfirmationEmail': async

