# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    # Ensure Symfony scans all controllers in the new folder structure
    App\Booking\UserInterface\Controller\:
        resource: '../src/Booking/UserInterface/Controller/'
        tags: ['controller.service_arguments']

    # If you add other domains, register their controllers similarly
    # App\Payments\UserInterface\Controller\:
    #    resource: '../src/Payments/UserInterface/Controller/'
    #    tags: ['controller.service_arguments']

    # This tells Symfony:
    # "When someone type-hints EventRepositoryInterface..."
    App\Booking\Domain\Repository\EventRepositoryInterface:
        # "...actually give them the DoctrineEventRepository service"
        alias: App\Booking\Infrastructure\Repository\DoctrineEventRepository
