name: CI Checks (PHPStan & CS)

on:
    push:
        branches: [ "main" ] # Запуск при пуші в гілку main
    pull_request:
        branches: [ "main" ] # Запуск при створенні/оновленні Pull Request

jobs:
    php_quality:
        name: Code Quality Checks
        runs-on: ubuntu-latest

        steps:
            - name: ⬇️ Checkout code
              uses: actions/checkout@v4

            - name: 🐳 Set up Docker Compose
                # Запускаємо ваші сервіси, як описано в docker-compose.yml
              run: docker compose up -d --build

            - name: ⏳ Wait for services to be ready
                # Чекаємо на повну готовність бази даних та RabbitMQ
              run: docker compose exec php-fpm sh -c "until nc -z database 5432; do echo Waiting for DB; sleep 1; done;"

            - name: 📦 Install Composer dependencies
                # Запуск Composer всередині Docker-контейнера
              run: docker compose exec php-fpm composer install --no-interaction --prefer-dist

            - name: 💿 Run Database Migrations
                # Створення схеми БД для тестів
              run: docker compose exec php-fpm php bin/console doctrine:migrations:migrate --no-interaction

            - name: ⚙️ Clear Symfony Cache
                # Очищення кешу перед аналізом
              run: docker compose exec php-fpm php bin/console cache:clear

            - name: 🛡️ Run PHPStan Static Analysis
                # Запуск PHPStan. Зверніть увагу на `--memory-limit` та прямий шлях!
              run: docker compose exec php-fpm ./vendor/bin/phpstan analyse src tests --level 9 --memory-limit=512M

            - name: 🎨 Run PHP-CS-Fixer Check
                # Перевірка стандартів кодування (dry-run). Якщо є порушення, пайплайн впаде.
              run: docker compose exec php-fpm ./vendor/bin/php-cs-fixer fix --dry-run --diff src tests

            # Опціонально, але рекомендовано: запуск PHPUnit тестів
            - name: ✅ Run PHPUnit Tests
              run: docker compose exec php-fpm php bin/phpunit
